# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import runtime_pb2 as runtime__pb2


class NodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/bazil.Node/Info',
                request_serializer=runtime__pb2.ExpertUID.SerializeToString,
                response_deserializer=runtime__pb2.ExpertInfo.FromString,
                )
        self.Backward = channel.stream_stream(
                '/bazil.Node/Backward',
                request_serializer=runtime__pb2.ExpertRequest.SerializeToString,
                response_deserializer=runtime__pb2.Tensor.FromString,
                )
        self.Forward = channel.stream_stream(
                '/bazil.Node/Forward',
                request_serializer=runtime__pb2.ExpertRequest.SerializeToString,
                response_deserializer=runtime__pb2.Tensor.FromString,
                )


class NodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Backward(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forward(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=runtime__pb2.ExpertUID.FromString,
                    response_serializer=runtime__pb2.ExpertInfo.SerializeToString,
            ),
            'Backward': grpc.stream_stream_rpc_method_handler(
                    servicer.Backward,
                    request_deserializer=runtime__pb2.ExpertRequest.FromString,
                    response_serializer=runtime__pb2.Tensor.SerializeToString,
            ),
            'Forward': grpc.stream_stream_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=runtime__pb2.ExpertRequest.FromString,
                    response_serializer=runtime__pb2.Tensor.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bazil.Node', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Node(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bazil.Node/Info',
            runtime__pb2.ExpertUID.SerializeToString,
            runtime__pb2.ExpertInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Backward(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/bazil.Node/Backward',
            runtime__pb2.ExpertRequest.SerializeToString,
            runtime__pb2.Tensor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Forward(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/bazil.Node/Forward',
            runtime__pb2.ExpertRequest.SerializeToString,
            runtime__pb2.Tensor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
