# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runtime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rruntime.proto\x12\x05\x62\x61zil\"\x18\n\tExpertUID\x12\x0b\n\x03uid\x18\x01 \x01(\t\"%\n\nExpertInfo\x12\x17\n\x0fserialized_info\x18\x01 \x01(\x0c\"N\n\rExpertRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x1e\n\x07tensors\x18\x02 \x03(\x0b\x32\r.bazil.Tensor\x12\x10\n\x08metadata\x18\x03 \x01(\x0c\"B\n\x0e\x45xpertResponse\x12\x1e\n\x07tensors\x18\x02 \x03(\x0b\x32\r.bazil.Tensor\x12\x10\n\x08metadata\x18\x03 \x01(\x0c\"\x89\x01\n\x06Tensor\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x02 \x03(\r\x12\x15\n\rrequires_grad\x18\x03 \x01(\x08\x12\r\n\x05\x64type\x18\x04 \x01(\t\x12+\n\x0b\x63ompression\x18\x05 \x01(\x0e\x32\x16.bazil.CompressionType\x12\x0e\n\x06\x63hunks\x18\x06 \x01(\x05*t\n\x0f\x43ompressionType\x12\x08\n\x04NONE\x10\x00\x12\x11\n\rMEANSTD_16BIT\x10\x01\x12\x0b\n\x07\x46LOAT16\x10\x02\x12\x11\n\rQUANTILE_8BIT\x10\x03\x12\x10\n\x0cUNIFORM_8BIT\x10\x04\x12\x12\n\x0e\x42LOCKWISE_8BIT\x10\x05\x32\xa2\x01\n\x04Node\x12-\n\x04Info\x12\x10.bazil.ExpertUID\x1a\x11.bazil.ExpertInfo\"\x00\x12\x35\n\x08\x42\x61\x63kward\x12\x14.bazil.ExpertRequest\x1a\r.bazil.Tensor\"\x00(\x01\x30\x01\x12\x34\n\x07\x46orward\x12\x14.bazil.ExpertRequest\x1a\r.bazil.Tensor\"\x00(\x01\x30\x01\x42!Z\x1fgithub.com/bazil-ai/bazil-protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037github.com/bazil-ai/bazil-proto'
  _COMPRESSIONTYPE._serialized_start=377
  _COMPRESSIONTYPE._serialized_end=493
  _EXPERTUID._serialized_start=24
  _EXPERTUID._serialized_end=48
  _EXPERTINFO._serialized_start=50
  _EXPERTINFO._serialized_end=87
  _EXPERTREQUEST._serialized_start=89
  _EXPERTREQUEST._serialized_end=167
  _EXPERTRESPONSE._serialized_start=169
  _EXPERTRESPONSE._serialized_end=235
  _TENSOR._serialized_start=238
  _TENSOR._serialized_end=375
  _NODE._serialized_start=496
  _NODE._serialized_end=658
# @@protoc_insertion_point(module_scope)
